### ISSUE TITLE
Disrupt | Progress Tracker

### ISSUE THREAD

**Issue by notscrappie** [shadowrunners/Disrupt#1]
# What is Disrupt?
Disrupt is an extremely experimental library used to stream audio from streaming services like Deezer, SoundCloud, Spotify and others. What differentiates Disrupt from the rest is the fact that it relies solely on Deezer as the "default" platform that it streams audio from with full native playback support (no searching on YouTube and playing the equivalent) and the custom solution that we've built with the help of other repositories who have documented the private APIs of Deezer.

This library is currently **extremely experimental** and a lot of things need to be implemented, so that's why I've created this issue in order to track the progress.

## To Do List
- [x] Remove the hardcoded track decryption key so that I don't get into legal trouble with Deezer or risk getting DMCA'd.
- [x] Better understand the @discordjs/voice package and create a Player system using it.
- [x] Create a full queue system.
- [x] Create a full Track system in order to pull information about the currently playing track (title, artist, ID etc).
- [x] Implement player events (such as trackStart, trackEnd and trackError).
- [x] Implement album support.
- [x] Implement playlist support.
- [x] Add native support for SoundCloud.
- [x] Add support for Spotify with searching via Deezer.
- [ ] Add volume editing support.
- [x] Enhance the requester system.
- [ ] Add seeking.
- [x] Add compatibility with [musicard](https://github.com/a3pire/musicard).

## Personal Notes
- ARLs are passed under a Cookie header during the first request that you send to the Deezer API (deezer.ping).
- Bandcamp doesn't have an API for generating song links, they instead store the link to the MP3 in an audio tag in the song's HTML page.
- ~~SoundCloud requires a client ID (probably gonna make the user provide their own) and does have a public API for getting stream URLs, gonna need to leave credit though.~~ Found an alternate way, will need to document.
- Deezer CheckForm token (API token) doesn't seem to reset itself if you previously pinged the endpoint, will most likely need to find a way to reset the cookie that controls this before pinging again with the URL in the cookie field.
- ~~For loops don't really work for albums or playlists. Mostly causes memory leaks, need to find an alternate way of fetching albums without performance going to shit.~~ Fixed this by implementing stream URL fetching upon the track entering a now playing state.
- ~~Will need to split off checkForm (API key) fetching into its own function that assigns the token to a variable inside the Deezer Manager. Most likely gonna make this an "init()" function that needs to be added to the bot's ready event file. Should speed up media URL fetching & song data fetching quite a bit since no more unnecessary requests are being done.~~ Added a check to the fetchMediaURL() function instead that will run if the sid or licenseToken aren't defined.
- Bandcamp stores their album / song information in a script element in their HTML instead of fetching from an API. Info is under a script with the type of application/ld+json.

This list might grow so, keep an eye out!
